name: tvmobi
favicon: null
layout_spectrum: 0.7526
typography_spectrum: 0.75434
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#949889'
    - '#000000'
    - '#820000'
    - '#65544a'
    - '#d0c8bc'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.4849624
  rhythmicContrast: 0.25
purpose: []
