name: tvmobi
favicon: null
layout_spectrum: 0.11898100981488824
typography_spectrum: 0.10857144324108958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101112'
    - '#fefce4'
    - '#b7c2ad'
    - '#b15047'
    - '#457aa7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.32917024102061987
  rhythmicContrast: 0.5
purpose: []
