name: tvmobi
favicon: null
layout_spectrum: 0.23961
typography_spectrum: 0.00431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121608'
    - '#8e090a'
    - '#3c3f24'
    - '#c26116'
    - '#f5b94d'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
