name: tvmobi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f7'
    - '#212124'
    - '#bcbcbe'
    - '#f17277'
    - '#606060'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.32917024102061987
  rhythmicContrast: 0.5
purpose: []
