name: tvmobi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101112'
    - '#fefce4'
    - '#b7c2ad'
    - '#b15047'
    - '#457aa7'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
